
import React from 'react';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';

export const IntroductionTab = () => {
  return (
  <div className="space-y-6">
    <Card className="bg-white/10 backdrop-blur-sm border-[#e5e1d8]/30">
      <CardHeader>
        <CardTitle className="text-[#e5e1d8] text-2xl uppercase tracking-wide">
          WHAT IS CARBON FOOTPRINT?
        </CardTitle>
        <CardDescription className="text-[#e5e1d8]/80">
          Understanding your environmental impact
        </CardDescription>
      </CardHeader>
      <CardContent className="text-[#e5e1d8] space-y-4">
        <p>
          A carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) 
          that are generated by our actions. It's usually measured in equivalent tons of CO₂ per year.
        </p>
        <p>
          The average carbon footprint for a person in the United States is 16 tons, one of the highest 
          rates in the world. Globally, the average is closer to 4 tons per person.
        </p>
      </CardContent>
    </Card>

    <Card className="bg-white/10 backdrop-blur-sm border-[#e5e1d8]/30">
      <CardHeader>
        <CardTitle className="text-[#e5e1d8] text-2xl uppercase tracking-wide">
          HOW IS IT CALCULATED?
        </CardTitle>
      </CardHeader>
      <CardContent className="text-[#e5e1d8] space-y-4">
        <div>
          <h3 className="text-xl font-semibold mb-2 uppercase text-green-300">EMISSION FACTORS</h3>
          <p>
            We use standard emission factors to convert your activities into CO₂ equivalent emissions:
          </p>
          <ul className="list-disc list-inside mt-2 space-y-1 marker:text-[#e5e1d8]">
            <li><strong>Electricity:</strong> 0.5 kg CO₂/kWh (varies by region)</li>
            <li><strong>Natural Gas:</strong> 5.3 kg CO₂/therm</li>
            <li><strong>Gasoline:</strong> 8.9 kg CO₂/gallon</li>
            <li><strong>Air Travel:</strong> 0.9 kg CO₂/mile (average)</li>
            <li><strong>Public Transport:</strong> 0.1 kg CO₂/mile</li>
            <li><strong>Food:</strong> Varies by type (meat: 6.6 kg CO₂/kg, dairy: 3.2 kg CO₂/kg)</li>
          </ul>
        </div>
      </CardContent>
    </Card>

    <Card className="bg-white/10 backdrop-blur-sm border-[#e5e1d8]/30">
      <CardHeader>
        <CardTitle className="text-[#e5e1d8] text-2xl uppercase tracking-wide">
          CATEGORIES WE MEASURE
        </CardTitle>
      </CardHeader>
      <CardContent className="text-[#e5e1d8]">
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
          <div>
            <h4 className="font-semibold text-green-300 mb-2 uppercase">DIRECT EMISSIONS</h4>
            <ul className="space-y-1 list-disc list-inside marker:text-[#e5e1d8]">
              <li>Home energy use (electricity, gas, heating)</li>
              <li>Personal transportation (car, motorbike)</li>
              <li>Direct fuel consumption</li>
            </ul>
          </div>
          <div>
            <h4 className="font-semibold text-green-300 mb-2 uppercase">INDIRECT EMISSIONS</h4>
            <ul className="space-y-1 list-disc list-inside marker:text-[#e5e1d8]">
              <li>Air travel and long-distance transport</li>
              <li>Public transportation</li>
              <li>Food consumption and diet choices</li>
              <li>Consumer goods and services</li>
            </ul>
          </div>
        </div>
      </CardContent>
    </Card>

    <Card className="bg-[#e5e1d8]/10 backdrop-blur-sm border-[#e5e1d8]/30">
      <CardHeader>
        <CardTitle className="text-[#e5e1d8] text-2xl uppercase tracking-wide">
          REDUCTION TARGETS
        </CardTitle>
      </CardHeader>
      <CardContent className="text-[#e5e1d8]">
        <p className="mb-4">
          To limit global warming to 1.5°C, the average person needs to reduce their carbon footprint to:
        </p>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-center">
          <div className="bg-[#e5e1d8]/20 rounded-lg p-4">
            <div className="text-2xl font-bold text-green-300">2.3 tons</div>
            <div className="text-sm">By 2030</div>
          </div>
          <div className="bg-[#e5e1d8]/20 rounded-lg p-4">
            <div className="text-2xl font-bold text-green-300">1.4 tons</div>
            <div className="text-sm">By 2040</div>
          </div>
          <div className="bg-[#e5e1d8]/20 rounded-lg p-4">
            <div className="text-2xl font-bold text-green-300">0.7 tons</div>
            <div className="text-sm">By 2050</div>
          </div>
        </div>
      </CardContent>
    </Card>
  </div>
);

};
